export const ActionType = {
  LOADING:'context/LOADING',
  SWITCH_APP: 'context/SWITCH_APP',
  SWITCH_AUTHENTICATED: 'context/SWITCH_AUTHENTICATED',
  GET_DATA_USER: 'context/GET_DATA_USER',
  GET_CONFIGURATION: 'context/GET_CONFIGURATION',
  GET_ROLES_USER: 'context/GET_ROLES_USER',
  FIELD_CHANGE: 'context/FIELD_CHANGE',
};
