version: '3.4'

services:
  AFRO-admin:
    image: nateteam/tyrant-admin:prod
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
