version: '3.4'

services:
  base-core-react:
    image: base-core-react
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
