version: '3.8'

services:
  base-core-react:
    container_name:  react-redux
    image: react-redux
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
