export const ActionType = {
  GET_ORDERS: 'order/GET_ORDERS',
  GET_ORDER: 'order/GET_ORDER',
  FIELD_CHANGE: 'order/FIELD_CHANGE',
  SHOW_NOTIFICATION: 'order/SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'order/HIDE_NOTIFICATION',
};
