export const ActionType = {
  GET_PRODUCTS: 'user/GET_PRODUCTS',
  GET_PRODUCT: 'user/GET_PRODUCT',
  FIELD_CHANGE: 'product/FIELD_CHANGE',
  SHOW_NOTIFICATION: 'product/SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'product/HIDE_NOTIFICATION',
};
